version: "3.8"
services:
  db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: rails_sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    command: bash -c "bash entrypoint.sh && /bin/bash"
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/app
    depends_on:
      - db
  nginx:
    image: nginx:1.23.1-alpine
    ports:
      - "81:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "app"
